server:
  port: 8081
  servlet:
    context-path: /demo-drools
spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true 
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate
